import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class CleanFile:
    path: str
    content: str
    language: str | None = None


@dataclass
class CleanReport:
    kept: list[CleanFile] = field(default_factory=list)
    skipped_empty: int = 0
    skipped_too_long_line: int = 0
    skipped_generated: int = 0
    skipped_vendor: int = 0
    removed_carriage_returns: int = 0
    normalized_bom: int = 0
    quality_flags: dict[str, int] = field(default_factory=dict)


GENERATED_MARKERS = re.compile(
    r"(auto-generated|automatically generated|generated by|do not edit[!\u2014]*|"
    r"this file is generated|@generated|swagger codegen|protoc |"
    r"eslint-disable.*generated|bundle\.js|\.min\.css)",
    re.IGNORECASE,
)
VENDOR_PATHS = re.compile(r"(^|/)(vendor|third_party|thirdparty|deps|external)/")

NO_BOM = lambda text: text.lstrip("\ufeff") if text.startswith("\ufeff") else text


def clean_text(text: str) -> tuple[str, list[str]]:
    flags = []
    original = text

    if text.startswith("\ufeff"):
        flags.append("bom-removed")
        text = text.lstrip("\ufeff")
    if "\r\n" in text:
        flags.append("crlf-normalized")
        text = text.replace("\r\n", "\n").replace("\r", "\n")

    lines = text.splitlines()
    normalized = [line.rstrip() for line in lines]
    text = "\n".join(normalized).strip()

    if not text:
        return text, ["empty"]

    too_long_line = max((len(line) for line in text.splitlines()), default=0) > 100_000
    if too_long_line:
        flags.append("too-long-line")

    if GENERATED_MARKERS.search(text[:2000]):
        flags.append("generated-marker")

    no_identifiers = not re.search(r"[A-Za-z_]{2,}", text)
    if no_identifiers:
        flags.append("no-identifiers")

    return text, flags


def clean_file(
    path: str | Path,
    drop_generated: bool = True,
    drop_vendor: bool = True,
    max_line: int = 100_000,
) -> CleanFile | None:
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    text, flags = clean_text(text)

    if "empty" in flags:
        return None
    if "too-long-line" in flags:
        return None
    if drop_generated and "generated-marker" in flags:
        return None
    rel = str(path).replace("\\", "/")
    if drop_vendor and VENDOR_PATHS.search(rel):
        return None

    return CleanFile(path=rel, content=text)


def clean_corpus(root: str | Path, destination: str | Path) -> CleanReport:
    report = CleanReport()
    root = Path(root)
    dest = Path(destination)
    dest.mkdir(parents=True, exist_ok=True)

    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        cleaned = clean_file(path)
        if cleaned is None:
            text, flags = clean_text(path.read_text(encoding="utf-8", errors="replace"))
            if "empty" in flags:
                report.skipped_empty += 1
            elif "too-long-line" in flags:
                report.skipped_too_long_line += 1
            elif "generated-marker" in flags:
                report.skipped_generated += 1
            continue

        out = dest / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(cleaned.content, encoding="utf-8")
        report.kept.append(cleaned)

    return report